# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from .. import _utilities

accountId: Optional[str]

authType: Optional[str]

azureClientId: Optional[str]

azureClientSecret: Optional[str]

azureEnvironment: Optional[str]

azureTenantId: Optional[str]

azureUseMsi: Optional[str]

azureWorkspaceResourceId: Optional[str]

configFile: Optional[str]

debugHeaders: Optional[str]

debugTruncateBytes: Optional[str]

googleServiceAccount: Optional[str]

host: Optional[str]

httpTimeoutSeconds: Optional[str]

password: Optional[str]

profile: Optional[str]

rateLimit: Optional[str]

skipVerify: Optional[str]

token: Optional[str]

username: Optional[str]

