# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from .. import _utilities

azureClientId: Optional[str]

azureClientSecret: Optional[str]

azureEnvironment: Optional[str]

azurePatTokenDurationSeconds: Optional[str]
"""
Currently secret scopes are not accessible via AAD tokens so we will need to create a PAT token
"""

azureResourceGroup: Optional[str]

azureSubscriptionId: Optional[str]

azureTenantId: Optional[str]

azureUsePatForCli: Optional[str]
"""
Create ephemeral PAT tokens also for AZ CLI authenticated requests
"""

azureUsePatForSpn: Optional[str]
"""
Create ephemeral PAT tokens instead of AAD tokens for SPN
"""

azureWorkspaceName: Optional[str]

azureWorkspaceResourceId: Optional[str]

configFile: Optional[str]
"""
Location of the Databricks CLI credentials file, that is created by `databricks configure --token` command. By default,
it is located in ~/.databrickscfg. Check https://docs.databricks.com/dev-tools/cli/index.html#set-up-authentication for
docs. Config file credentials will only be used when host/token are not provided.
"""

debugHeaders: Optional[str]
"""
Debug HTTP headers of requests made by the provider. Default is false. Visible only when TF_LOG=DEBUG is set
"""

debugTruncateBytes: Optional[str]
"""
Truncate JSON fields in JSON above this limit. Default is 96. Visible only when TF_LOG=DEBUG is set
"""

host: Optional[str]

password: Optional[str]

profile: Optional[str]
"""
Connection profile specified within ~/.databrickscfg. Please check
https://docs.databricks.com/dev-tools/cli/index.html#connection-profiles for documentation.
"""

rateLimit: Optional[str]
"""
Maximum number of requests per second made to Databricks REST API by Terraform.
"""

skipVerify: Optional[str]
"""
Skip SSL certificate verification for HTTP calls. Use at your own risk.
"""

token: Optional[str]

username: Optional[str]

